apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app-deployment
  labels:
    project: calculatorapp
    app: calculator-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      project: calculatorapp
      app: calculator-app
  template:
    metadata:
      labels:
        project: calculatorapp
        app: calculator-app
    spec:
      containers:
        - name: calculator-app
          image: livisekar/simple-calculator:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: configmap-volume
              mountPath: /conf/map
      volumes:
        - name: configmap-volume
          configMap:
            name: calculator-app-config
          

---

apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  labels:
    project: calculatorapp
    app: calculator-app
spec:
  type: NodePort
  selector:
    project: calculatorapp
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036